[package]
name = "codecov-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.4", features = ["sqlite"] }
diesel_migrations = "2.1.0"
diesel-derive-enum = { version = "2.1.0", features = ["sqlite"] }

[dev-dependencies]
tempfile = "3.9.0"
